# Generated by Django 6.0.2 on 2026-02-05 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Ссылка (slug)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фото категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото товара')),
                ('price_retail', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена розничная')),
                ('price_wholesale', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена оптовая')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='Остаток на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
