# Generated by Django 6.0.2 on 2026-05-31 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_banner_alter_product_options_category_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Имя покупателя')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('contact_method', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('callback', 'Заказ звонка'), ('call', 'Позвонит сам')], default='telegram', max_length=20, verbose_name='Способ связи')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В работе'), ('done', 'Выполнен'), ('canceled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('total_retail', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Сумма (розница)')),
                ('total_wholesale', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Сумма (опт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='СтройМаг', max_length=100, verbose_name='Название магазина')),
                ('accent_color', models.CharField(default='#2c7be5', help_text='Главный цвет кнопок и акцентов, например #2c7be5', max_length=7, verbose_name='Акцентный цвет (hex)')),
                ('phone', models.CharField(blank=True, help_text='Для кнопки «Позвонить» и заказа звонка', max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email для заказов')),
                ('telegram_username', models.CharField(blank=True, max_length=50, verbose_name='Telegram (username без @)')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp (только цифры, напр. 79990000000)')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Часы работы')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок на главной')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок на главной')),
                ('enable_telegram', models.BooleanField(default=True, verbose_name='Канал: Telegram')),
                ('enable_whatsapp', models.BooleanField(default=False, verbose_name='Канал: WhatsApp')),
                ('enable_email', models.BooleanField(default=False, verbose_name='Канал: Email')),
                ('enable_callback', models.BooleanField(default=True, verbose_name='Канал: Заказ звонка')),
                ('enable_call', models.BooleanField(default=True, verbose_name='Канал: Позвонить самому')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='Товар (снапшот)')),
                ('size', models.CharField(default='Стандарт', max_length=50, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_retail', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена розн. (снапшот)')),
                ('price_wholesale', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена опт. (снапшот)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
