# Generated by Django 6.0.2 on 2026-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_sitesettings_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_method',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('callback', 'Позвоните мне'), ('call', 'Позвоню сам')], default='telegram', max_length=20, verbose_name='Способ связи'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_call',
            field=models.BooleanField(default=True, verbose_name='Канал: Позвоню сам'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_callback',
            field=models.BooleanField(default=True, verbose_name='Канал: Позвоните мне'),
        ),
    ]
