# Generated by Django 6.0.2 on 2026-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Фон-фото на главной (строители и т.п.)'),
        ),
    ]
