# Generated by Django 6.0.2 on 2026-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sitesettings_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo/', verbose_name='Фон баннера'),
        ),
    ]
