# Generated by Django 6.0.2 on 2026-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_lat',
            field=models.CharField(blank=True, max_length=20, verbose_name='Координата: широта (напр. 55.616066)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_lon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Координата: долгота (напр. 37.482762)'),
        ),
    ]
