# Generated by Django 6.0.2 on 2026-06-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_sitesettings_map_lat_sitesettings_map_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-box', '📦 Коробка (по умолчанию)'), ('fa-bed', '🛏 Матрас / кровать'), ('fa-mattress-pillow', '🛏 Матрас с подушкой'), ('fa-couch', '🛋 Мебель / диван'), ('fa-shirt', '👕 Одежда'), ('fa-helmet-safety', '⛑ Спецодежда / каска'), ('fa-socks', '🧦 Текстиль / носки'), ('fa-toolbox', '🧰 Инструменты'), ('fa-screwdriver-wrench', '🔧 Инструмент / крепёж'), ('fa-trowel-bricks', '🧱 Стройматериалы'), ('fa-paint-roller', '🎨 Отделка / малярка'), ('fa-ruler-combined', '📐 Замеры / размеры'), ('fa-truck', '🚚 Доставка'), ('fa-warehouse', '🏬 Склад'), ('fa-tags', '🏷 Распродажа'), ('fa-fire', '🔥 Хиты')], default='fa-box', help_text='Показывается в плитках каталога', max_length=40, verbose_name='Иконка'),
        ),
    ]
