# Generated by Django 6.0.2 on 2026-06-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(default=False, verbose_name='Хит продаж (бейдж)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Фон-фото на странице «О магазине»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Если остаток ≤ этого числа — бейдж «Мало осталось»', verbose_name='Порог «мало осталось»'),
        ),
    ]
