# Generated by Django 6.0.2 on 2026-06-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_is_hit_sitesettings_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-box', '📦 Коробка (по умолчанию)'), ('fa-bed', '🛏 Матрас / кровать'), ('fa-mattress-pillow', '🛏 Матрас с подушкой'), ('fa-couch', '🛋 Мебель / диван'), ('fa-chair', '🪑 Мебель / стул'), ('fa-shirt', '👕 Одежда'), ('fa-helmet-safety', '⛑ Спецодежда / каска'), ('fa-socks', '🧦 Текстиль / носки'), ('fa-shoe-prints', '👟 Обувь'), ('fa-baby', '👶 Детское'), ('fa-utensils', '🍴 Посуда / столовые приборы'), ('fa-kitchen-set', '🍳 Кухня / кухонная утварь'), ('fa-mug-hot', '☕ Кружки / посуда'), ('fa-bowl-food', '🥣 Посуда / миски'), ('fa-seedling', '🌱 Сад / рассада'), ('fa-leaf', '🍃 Сад / растения'), ('fa-tree', '🌳 Сад / деревья'), ('fa-shovel', '🪏 Садовый инструмент'), ('fa-toolbox', '🧰 Инструменты'), ('fa-screwdriver-wrench', '🔧 Инструмент / крепёж'), ('fa-hammer', '🔨 Молоток / инструмент'), ('fa-wrench', '🔧 Ключи / сантех.инструмент'), ('fa-trowel-bricks', '🧱 Стройматериалы'), ('fa-ruler-combined', '📐 Замеры / размеры'), ('fa-paint-roller', '🎨 Отделка / малярка'), ('fa-brush', '🖌 Кисти'), ('fa-fill-drip', '🪣 Краски / ЛКМ'), ('fa-faucet', '🚰 Сантехника'), ('fa-shower', '🚿 Душ / ванная'), ('fa-toilet', '🚽 Сантехника / унитазы'), ('fa-bolt', '⚡ Электрика'), ('fa-plug', '🔌 Электрика / розетки'), ('fa-lightbulb', '💡 Свет / лампы'), ('fa-door-open', '🚪 Двери'), ('fa-key', '🔑 Замки / фурнитура'), ('fa-broom', '🧹 Хозтовары / уборка'), ('fa-bucket', '🪣 Хозтовары / вёдра'), ('fa-spray-can', '🧴 Бытовая химия'), ('fa-fan', '🌀 Вентиляция'), ('fa-snowflake', '❄ Климат / охлаждение'), ('fa-temperature-half', '🌡 Отопление'), ('fa-car', '🚗 Авто / гараж'), ('fa-truck', '🚚 Доставка'), ('fa-warehouse', '🏬 Склад'), ('fa-tags', '🏷 Распродажа'), ('fa-fire', '🔥 Хиты')], default='fa-box', help_text='Показывается в плитках каталога', max_length=40, verbose_name='Иконка'),
        ),
    ]
