# Generated by Django 6.0.2 on 2026-06-02 00:38

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=200, validators=[store.models.validate_safe_link], verbose_name='Ссылка (например /category/matrasy/)'),
        ),
    ]
