# Generated by Django 6.0.2 on 2026-06-02 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = без скидки. Напр. 20 = −20% к розничной цене.', validators=[django.core.validators.MaxValueValidator(95)], verbose_name='Скидка, %'),
        ),
    ]
