# Generated by Django 6.0.2 on 2026-06-02 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_target',
            field=models.CharField(choices=[('retail', 'Только розница'), ('wholesale', 'Только опт'), ('both', 'Розница и опт')], default='retail', max_length=10, verbose_name='Скидка применяется к'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = без скидки. Напр. 20 = −20%.', validators=[django.core.validators.MaxValueValidator(95)], verbose_name='Скидка, %'),
        ),
    ]
