# Generated by Django 6.0.2 on 2026-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_discount_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Код для проверки заказа покупателем (генерируется автоматически)', max_length=12, verbose_name='Код заказа'),
        ),
    ]
