# Generated by Django 6.0.2 on 2026-06-02 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = без скидки. Применяется к товарам категории, у которых НЕТ своей скидки (не суммируется).', validators=[django.core.validators.MaxValueValidator(95)], verbose_name='Скидка на категорию, %'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount_target',
            field=models.CharField(choices=[('retail', 'Только розница'), ('wholesale', 'Только опт'), ('both', 'Розница и опт')], default='retail', max_length=10, verbose_name='Скидка категории применяется к'),
        ),
    ]
