# Generated by Django 6.0.2 on 2026-06-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_category_discount_percent_category_discount_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Доп. фото')),
                ('sort', models.PositiveIntegerField(default=0, help_text='Чем меньше — тем раньше', verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Фото товара (галерея)',
                'verbose_name_plural': 'Фото товара (галерея)',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
